export const RTM_ACTION_TYPE = {
  SET_RTM_CLIENT: "SET_RTM_CLIENT",
  ADD_NEW_MESSAGE: "ADD_NEW_MESSAGE",
  // ADD_RTM_USER: "ADD_RTM_USER",
  CLEAR_MESSAGE: "CLEAR_MESSAGE",
  CLEAR_CLIENT_CHANNEL: "CLEAR_CLIENT_CHANNEL",
  SET_CHANNEL: "SET_CHANNEL",
};
