export const USER_ACTION_TYPE = {
  SET_CURRENT_USER: "user/SET_CURRENT_USER",
  SET_USER_ROOMINFO: "user/SET_USER_ROOMINFO ",
  SET_ISLOADING: "user/SET_ISLOADING",
  TOGGLE_SIGN_FORM: "user/TOGGLE_SIGN_FORM",

  // GOOGLE_SIGN_IN_START: "user/GOOGLE_SIGN_IN_START",
  // EMAIL_SIGN_IN_START: "user/EMAIL_SIGN_IN_START",
  // SIGN_IN_SUCCESS: "user/SIGN_IN_SUCCESS",
};
