export const RTC_ACTION_TYPE = {
  ADD_RTC_USER: "ADD_RTC_USER",
  SET_RTC_USER: "SET_RTC_USER",
  SET_LOCAL_USER: "SET_LOCAL_USER",
  CLEAR_RTC_USER: "CLEAR_RTC_USER",
  TOGGLE_RTC_SHARE: "TOGGLE_RTC_SHARE",
};
